// <auto-generated />
namespace CPAngular2.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161143162_addEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
